---
title: "Generating The Figures"
author: "Sina Aghaei"
date: "10/24/2020"
output: 
  # flexdashboard::flex_dashboard:
  #   orientation: columns
  html_document:
    # number_sections: true
 
---


In this script we provide the code for generating the figures in the paper.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE )
library(kableExtra)
library(png)
library(ggplot2)
library(reshape2)
library(egg)
require(tidyr)
library(dplyr)
library(plyr)
library(latex2exp)
# library(ggpubr)
library(data.table)
library(RColorBrewer)
library(MASS)
require(scales)
rm(list=ls())

data_train= read.csv('./../Results/paper results/train.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 
data_test= read.csv('./../Results/paper results/test.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 

forpres=TRUE
if (forpres){
  fontfam = "sans"
} else {
  fontfam = "serif"
}

figure_path = "./"


data_train$sample <- as.factor(data_train$sample)
data_train$depth <- as.factor(data_train$depth)

data_test$sample <- as.factor(data_test$sample)
data_test$depth <- as.factor(data_test$depth)

#Let's sort the levels of approach such that the oldest method appears first
data_train$approach<- factor(data_train$approach, levels = c("OCT","BinOCT","FlowOCT","BendersOCT"))
data_test$approach<- factor(data_test$approach, levels = c("OCT","BinOCT","FlowOCT","BendersOCT"))

#Let's sort the levels of dataset with respect to their size
data_train$dataset <- factor(data_train$dataset, levels = as.character(unique(data_train[order(data_train$nrow),]$dataset)))
data_test$dataset <- factor(data_test$dataset, levels = as.character(unique(data_train[order(data_train$nrow),]$dataset)))

```


# In sample results

## Number of instances solved to optimality; No Regularization

```{r echo=TRUE, warning=FALSE}
####################################################################### 
#Time data
####################################################################### 
tmp <- subset(data_train, data_train$regularization == FALSE &  data_train$status %in% c(2,101,102))

tmp <- tmp[order(tmp$solving_time),]
tmp$numOfInstances <- rowidv(tmp, cols="approach")
tmp <- tmp[,c("approach","solving_time","numOfInstances")]
names(tmp) <- c("Approach","solving_time","numOfInstances")

tmp[nrow(tmp) + 1,] = list("OCT","3600",max(subset(tmp, tmp$Approach=="OCT")$numOfInstances))
tmp[nrow(tmp) + 1,] = list("BinOCT","3600",max(subset(tmp, tmp$Approach=="BinOCT")$numOfInstances))
tmp[nrow(tmp) + 1,] = list("FlowOCT","3600",max(subset(tmp, tmp$Approach=="FlowOCT")$numOfInstances))
tmp[nrow(tmp) + 1,] = list("BendersOCT","3600",max(subset(tmp, tmp$Approach=="BendersOCT")$numOfInstances))

tmp$solving_time <- as.numeric(as.character(tmp$solving_time))
tmp$numOfInstances <- as.numeric(as.character(tmp$numOfInstances))

tmp$Approach  <- factor(tmp$Approach , levels = c("BendersOCT", "FlowOCT", "BinOCT","OCT"))
tmp <- tmp[order(tmp$Approach),]

tmp_time <- tmp
rm(tmp)
####################################################################### 
#Gap data
####################################################################### 
tmp <- subset(data_train, data_train$regularization == FALSE &  !(data_train$status %in% c(2,101,102)))[,c('approach','gap')]#
tmp$gap <- format(round(tmp$gap, 2), nsmall = 5)

tmp <- tmp[order(tmp$gap),]
tmp <- tmp[order(tmp$approach),]

tmp$numOfInstances <- rowidv(tmp, cols=c("approach"))
tmp <- tmp[,c("approach","gap","numOfInstances")]
names(tmp) <- c("Approach","gap","numOfInstances")

tmp <- ddply(tmp, .(Approach, gap), function(x) x[which.max(x$numOfInstances),])


tmp$numOfInstances[tmp$Approach == "OCT"] <- tmp$numOfInstances[tmp$Approach == "OCT"] + max(subset(tmp_time, tmp_time$Approach=="OCT")$numOfInstances)
tmp$numOfInstances[tmp$Approach == "BinOCT"] <- tmp$numOfInstances[tmp$Approach == "BinOCT"] + max(subset(tmp_time, tmp_time$Approach=="BinOCT")$numOfInstances)
tmp$numOfInstances[tmp$Approach == "FlowOCT"] <- tmp$numOfInstances[tmp$Approach == "FlowOCT"] + max(subset(tmp_time, tmp_time$Approach=="FlowOCT")$numOfInstances)
tmp$numOfInstances[tmp$Approach == "BendersOCT"] <- tmp$numOfInstances[tmp$Approach == "BendersOCT"] + max(subset(tmp_time, tmp_time$Approach=="BendersOCT")$numOfInstances)

tmp[nrow(tmp) + 1,] = list("OCT","0",max(subset(tmp_time, tmp_time$Approach=="OCT")$numOfInstances))
tmp[nrow(tmp) + 1,] = list("BinOCT","0",max(subset(tmp_time, tmp_time$Approach=="BinOCT")$numOfInstances))
tmp[nrow(tmp) + 1,] = list("FlowOCT","0",max(subset(tmp_time, tmp_time$Approach=="FlowOCT")$numOfInstances))
tmp[nrow(tmp) + 1,] = list("BendersOCT","0",max(subset(tmp_time, tmp_time$Approach=="BendersOCT")$numOfInstances))

tmp$gap <- as.numeric(as.character(tmp$gap))
tmp$numOfInstances <- as.numeric(as.character(tmp$numOfInstances))

tmp$Approach  <- factor(tmp$Approach , levels = c("BendersOCT", "FlowOCT", "BinOCT","OCT"))
tmp <- tmp[order(tmp$gap),]
tmp <- tmp[order(tmp$Approach),]

tmp_gap <- tmp
rm(tmp)
####################################################################### 
####################################################################### 


colors <- c( brewer.pal(4, 'Set1')[3], brewer.pal(4, 'Set1')[2], brewer.pal(4, 'Set1')[4], brewer.pal(4, 'Set1')[1] ) #c("firebrick1 == 1","violetred==4","seagreen4==3","royalblue==2")
shapes <- c(15,16,17,4)
g1 <- ggplot(data = tmp_time, aes(x=solving_time, y=numOfInstances, group=Approach,color=Approach)) +
  geom_line(size=0.5)+ #aes(linetype=Approach)
  geom_point(aes(shape=Approach),size=2)+ 
  labs(x="Time (s)", y = "Number of Instances Solved")+
  scale_color_manual(values=colors)+
  scale_shape_manual(values=shapes)+
  theme(legend.position = "right",text = element_text(size=14,family=fontfam)) #14
print(g1)

g2 <- ggplot(data = tmp_gap, aes(x=gap*100, y=numOfInstances, group=Approach,color=Approach)) +
  geom_line(size=0.5)+ #aes(linetype=Approach)
  geom_point(aes(shape=Approach),size=2)+ 
  labs(x="Gap (%)", y = "Number of Instances Solved")+
  scale_color_manual(values=colors)+
  scale_shape_manual(values=shapes)+
  theme(legend.position = "right",text = element_text(size=14,family=fontfam)) #14
print(g2)





tmp_gap_1 <- tmp_gap
names(tmp_gap_1) <- c("Approach", "X", "numOfInstances")
tmp_gap_1$X <- tmp_gap_1$X*3600 + 3605
tmp_time_1 <- tmp_time
names(tmp_time_1) <- c("Approach", "X", "numOfInstances")
tmp <- rbind(tmp_time_1, tmp_gap_1)
rm(tmp_time_1, tmp_gap_1)

g3 <- ggplot(data = tmp, aes(x=X, y=numOfInstances, group=Approach,color=Approach)) +
  geom_line(size=0.5)+ #aes(linetype=Approach)
  # geom_point(aes(shape=Approach),size=2)+ 
  geom_vline(xintercept=3600, linetype = "dashed") +
  labs(x="X", y = "Number of Instances Solved")+
  scale_color_manual(values=colors)+
  scale_shape_manual(values=shapes)+
  scale_x_continuous(breaks=c(0,1200,2400,3605,4685,5765,7205), labels = c("0","1200","2400","0%","30%","60%","100%"))+
  theme(axis.text = element_text(size = 25),
        legend.position = "right", legend.key.size = unit(1, "cm"),
        legend.text = element_text(size = 50),
        legend.title = element_text(size = 60),
        text = element_text(family=fontfam),
        axis.title = element_text(size = 40)) + theme_classic() #14
print(g3)
```

